# Generated by Django 2.2.6 on 2019-11-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OurProject', '0002_auto_20191103_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='shirt',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='picture_of_shirt',
            field=models.ImageField(height_field='Shirt.image_height', upload_to='C:/django1/virtual3/ItraProject', width_field='Shirt.image_width'),
        ),
    ]
