# Generated by Django 2.2.6 on 2019-11-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OurProject', '0003_auto_20191103_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='picture_of_shirt',
            field=models.ImageField(height_field='image_height', upload_to='images', width_field='image_width'),
        ),
    ]
